pkg/controllers/spannerautoscaler_controller.go, pkg/controllers/spannerautoscaler_controller_test.go
It will take a few seconds to execute Cloud Spanner Update Instance API and changes take effect.
This causes the Cloud Spanner Update Instance API to execute many times until the changes take effect, as shown below:
<detail>
```
2020-06-09T00:03:32.434Z	INFO	controllers.spannerautoscaler	updated nodes via google cloud api	{"namespaced name": "spanner-autoscaler/spannerautoscaler-sample", "before": 1, "after": 5}
2020-06-09T00:03:32.434Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"SpannerAutoscaler","namespace":"spanner-autoscaler","name":"spannerautoscaler-sample","uid":"995dd40f-a9e1-11ea-8797-42010a920105","apiVersion":"spanner.mercari.com/v1alpha1","resourceVersion":"14404"}, "reason": "Updated", "message": "Updated number of nodes from 1 to 5"} …
```
=> Suppress UpdateInstance API from being executed unnecessarily

README.md, pkg/metrics/metrics.go
- The prerequisite API is `monitoring.googleapis.com`, not `serviceusage.googleapis.com`, so we need to fix it
- Remove `hl=ja` from URL
Fixes #
=> Fix readme and comment

pkg/controllers/spannerautoscaler_controller.go, pkg/syncer/syncer.go
Currently, errors in `syncer`'s unexported method are not being sent as Kubernetes events.
Custom Resource users will be able to check errors such as GetInstance and GetInstanceMetrics API for Cloud Spanner.
Example as follows:
```console
$ kubectl get events -n spanner-autoscaler
LAST SEEN   TYPE      REASON                 OBJECT                                             MESSAGE
...
5m59s       Warning   FailedSpannerAPICall   spannerautoscaler/spannerautoscaler-sample         no such spanner instance metrics
59s         Warning   FailedSpannerAPICall   spannerautoscaler/spannerautoscaler-sample         rpc error: code = NotFound desc = Instance not found: projects/myproject/instances/test-instance
```
Fixes #
=> Add EventRecorder to syncer

pkg/controllers/spannerautoscaler_controller.go
Currently, when the number of nodes is increased/decreased the message is as follows:
>Updated number of nodes from 2 to 1
Add the project ID and instance ID to the message to make it easier to identify which GCP project and Spanner instance the event occurred in.
Fixes #
=> Add project id and instance id to kubernetes event

cmd/spanner-autoscaler/main.go, pkg/controllers/spannerautoscaler_controller.go, pkg/controllers/spannerautoscaler_controller_test.go
Currently, all log levels are logged in the stderr.
Logs such as the `Info()` should be output to the stdout.
Fixes #
=> Set OutputPaths to zap

cmd/spanner-autoscaler/main.go, pkg/controllers/spannerautoscaler_controller.go, pkg/controllers/spannerautoscaler_controller_test.go
- Fix https://github.com/mercari/spanner-autoscaler/pull/23
- The log format changes are as follows:
```
2020-09-10T09:30:49.791Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "spannerautoscaler", "source": "kind source: /, Kind="}
```
```
{"level":"info","timestamp":1599740678066.0408,"logger":"controller-runtime.controller","message":"Starting EventSource","controller":"spannerautoscaler","source":"kind source: /, Kind="}
```
Fixes #
=> Fix logger configuration

README.md, config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml, pkg/api/v1alpha1/spannerautoscaler_types.go, pkg/controllers/spannerautoscaler_controller.go, pkg/controllers/spannerautoscaler_controller_test.go, pkg/spanner/spanner.go, pkg/syncer/syncer.go, pkg/syncer/syncer_test.go
To keep compatibility, this PR simply adds
- spec
- maxProcessingUnits
- minProcessingUnits
- status
- desiredProcessingUnits
- currentProcessingUnits
and support both of `*ProcessingUnits` and `*Nodes`.
In wording, I want to propose:
* Use "compute capacity" as the abstract term.
* Use "processing units(PU)" as the base unit for compute capacity.
* Use "nodes" as the supplementary unit which is equals to 1000 PU.
See also https://cloud.google.com/spanner/docs/compute-capacity?hl=en for the official use of these terms.
Fixes #26
=> Support Processing Units

.github/release.yml, .github/workflows/check-tag-bump.yml, .github/workflows/release.yml, .github/workflows/tag.yml
* Separate the tagging and the release workflows so that a manual tag can also trigger a release
* Upgrade `docker/build-push-action` to `v2`
* Add `name` to workflow steps, for better readability
* Add automated release notes generation using the corresponding feature from Github
Fixes #49
=> Improvements to release process

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile, cmd/spanner-autoscaler/main.go, pkg/controllers/spannerautoscaler_controller.go, pkg/metrics/metrics.go, pkg/syncer/syncer.go
* Add updated config for `golangci-lint`
* Fix current lint errors
* Add `make` targets for downloading and running lint checks
* Add Actions workflow for running lint checks 
Fixes #46
=> Enable `golangci-lint` checks

.goreleaser.yml
Fix Broken CI - https://github.com/mercari/spanner-autoscaler/runs/4849637737?check_suite_focus=true#step:4:39
=> Fix `main.go` path in `.goreleaser.yml`

.github/workflows/release.yml, .github/workflows/tag.yml
Fix the bug we hit - https://github.community/t/reusable-workflows-secrets-and-environments/203695/6
This was preventing the release workflow from logging in to DockerHub (due to missing secrets access).
EDIT: Reference doc for this - https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
=> Fix the CI workflows to pass secrets

.github/workflows/golangci-lint.yml, Makefile
Currently, we cannot determine the golangci-lint version since its version is not fixed. This is inconvenient from the developer's point of view so I fixed it to v1.44.0 which is the latest version as of today.
None
=> Use the same golangci-lint version in the Dev and the CI env

api/v1alpha1/spannerautoscaler_conversion.go, api/v1beta1/spannerautoscaler_types.go, api/v1beta1/spannerautoscaler_webhook.go, api/v1beta1/spannerautoscaler_webhook_test.go, config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml, controllers/spannerautoscaler_controller.go, controllers/spannerautoscaler_controller_test.go, pkg/syncer/syncer_test.go
- convert all internal functions to use only processing-units for computations
- remove some unnecessary functions to make the codebase smaller, readable and cleaner
- update/re-generate CRD (automatic, through `make manifests`)
=> Switch all internal compute capacity to processing units only

.github/workflows/release.yml, .goreleaser.yml, go.mod
The last CI job has failed (3 unsuccessful attempts) - https://github.com/mercari/spanner-autoscaler/actions/runs/1782580338
Probably because of cache... or some other missing dependency...
As a fix:
- setup golang before running `goreleaser`
- download the dependencies beforehand [[Ref](https://goreleaser.com/customization/build/#go-modules)],
=> Fix CI: goreleaser

.github/workflows/test.yml
I noticed the GitHub Actions go mod cache prefix was wrong and we cannot utilize the cache properly so I fixed that. Thanks!
None
=> Correct GitHub Actions go mod cache prefix

api/v1alpha1/spannerautoscaler_conversion_test.go
Added unit tests for v1alpha1 ConvertFrom. Thank you for your review!
None
=> Add unit tests for v1alpha1 ConvertFrom

config/crd/bases/spanner.mercari.com_spannerautoscaleschedules.yaml, controllers/spannerautoscaler_controller.go, controllers/spannerautoscaleschedule_controller.go, main.go
- Add `delete` functionality for `SpannerAutoscaleSchedule` resources so that whenever a schedule resource is deleted, it should also de-register the schedule from the spanner-atuoscaler (implementation [ref](https://book.kubebuilder.io/reference/using-finalizers.html))
- Rename the import of `syncer` package to `syncerpkg`, to avoid confusion with the variable of the same name
=> Add `delete` functionality for schedule resources

Makefile, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, main.go
Switched from command line flags to config file-based options. 
https://book.kubebuilder.io/component-config-tutorial/tutorial.html
None
```
make kind-cluster-reset
export IMG=mercari/spanner-autoscaler:local
make docker-build && make kind-load-docker-image
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
make deploy
```
=> Switch from command line flags to config file based options

Makefile, config/samples/rbac/role.yaml, config/samples/spanner_v1beta1_spannerautoscaler.yaml, config/samples/spanner_v1beta1_spannerautoscaleschedule.yaml
- Add `namespace` to new version samples
- Fix RoleBinding subject `kind` (the provided subject is actually a `Role` and not a `CluserRole`)
- Install cert-manager by default when Kind cluster is reset
Fixes #
=> Fix `RoleBinding` and `namespace` in samples

.github/workflows/golangci-lint.yml
Latest version of Go (v1.18) breaks the golangci-lint versions <= v1.45
Fix the version of golang to v1.17 for `golangci-lint` workflow
- Broken CI runs: https://github.com/mercari/spanner-autoscaler/runs/5964529973?check_suite_focus=true
- https://github.com/golangci/golangci-lint/issues/2374#issuecomment-1069029422
=> Freeze Go version for `golangci-lint`

PROJECT, api/v1beta1/spannerautoscaleschedule_webhook.go, api/v1beta1/webhook_suite_test.go, config/deploy-dev/kustomization.yaml, config/webhook/manifests.yaml, controllers/spannerautoscaler_controller.go, internal/scheduler/scheduler.go, main.go
- Add validation webhook for `SpannerAutoscaleSchedule`, which does the following:
- block changes to `TargetResource` and `Schedule` after resource creation
- validate that `Schedule.Cron` and `Schedule.Duration` can be parsed correctly
- ~validate that `Schedule.Duration` is smaller than the time period of the `Schedule.Cron` job (if this is not checked, then there can be a cascading scale-up trigger when the next cron job is run before the duration of the previous one is over)~
- Modify the implementation of the `scheduler` package so that a `schedule` is created for each `SpannerAutoscaler` instance (earlier, there was just one `scheduler` which was responsible for updating all `SpannerAutoscaler` resources)
EDIT:
- validation for schedule duration overlap has been removed because it …
=> Add validation webhook for `SpannerAutoscaleSchedule`

controllers/spannerautoscaler_controller.go, main.go
- rename some log keys to [common naming convention](https://pkg.go.dev/github.com/go-logr/logr#hdr-Key_Naming_Conventions)
- remove the default values for command line options
- make `leaderElectionID` configurable
- remove unnecessary `healthzEndpoin` and `readyzEndpoint` because they were default values already
Currently, the parameters which have default values from the command line, can not be overridden by the config file. This PR fixes this behavior.
=> Honor config-file options

docs/crd-reference.md
Adds additional information for scaleDownStepSize.
```diff
- | `scaledownStepSize` _integer_ | The maximum number of processing units which can be deleted in one scale-down operation
+ | `scaledownStepSize` _integer_ | The maximum number of processing units which can be deleted in one scale-down operation. Should be a multiple of 1000. |
```
~Fixes #~ Did not create an issue since it's just a doc fix. Please let me know if I should also create an issue.
I used a `scaledownStepSize` of 500, and received the following error.
```
The SpannerAutoscaler "spanner-autoscaler" is invalid
: spec.scaleConfig.scaledownStepSize: Invalid value: 500
: spec.scaleConfig.scaledownStepSize in body should be a multiple of 1000
```
This information is missing from the documentation, so I think it can save …
=> Add additional information for `scaledownStepSize`

Makefile
> `go get` no longer builds or installs packages in module-aware mode.
> https://go.dev/doc/go1.18#go-command
So let's migrate to `go install`.
```console
$ rm -f bin/*
$ make deps
Installing sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0
Installing sigs.k8s.io/kustomize/kustomize/v4@v4.5.7
Installing sigs.k8s.io/kind@v0.11.1
Installing github.com/GoogleContainerTools/kpt@main
Installing github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.0
Installing github.com/elastic/crd-ref-docs@v0.0.8
$ ls -l bin/
total 398800
-rwxr-xr-x  1 tkuchiki  tkuchiki  20997664 10 27 12:38 controller-gen
-rwxr-xr-x  1 tkuchiki  tkuchiki  17907024 10 27 12:38 crd-ref-docs
-rwxr-xr-x  1 tkuchiki  tkuchiki  38642240 10 27 12:38 golangci-lint
-rwxr-xr-x  1 tkuchiki  tkuchiki   9050576 10 27 12:38 …
```
=> Migrate from `go get` to `go install`

.github/workflows/size.yml
- Attempt to fix the permissions for workflow applying size labels to PRs (maybe https://github.com/mercari/spanner-autoscaler/pull/99 PR will pass size label CI job/checks after this PR is merged)
Rationale behind this: 
> Every pull request is an issue, but not every issue is a pull request. For this reason, "shared" actions for both features, like managing assignees, labels, and milestones, are provided within the Issues endpoints. [^github-doc-ref]
[^github-doc-ref]: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#about-labels
=> Add permisisons to CI for adding size labels

.github/workflows/size.yml
The currently used `actions-ecosystem/action-remove-labels` and
`actions-ecosystem/action-add-labels` [seem unmaintained](https://github.com/actions-ecosystem/action-add-labels/pull/434) and don't work
anymore because of using deprecated Nodejs 12 version.
Therefore, migrate to a better maintained solution.
=> Migrate to `actions/github-script` Github Action 

.github/workflows/tag.yml
- SSIA
- Fix GitHub Actions configuration
Fixes https://github.com/mercari/spanner-autoscaler/actions/runs/7456959858/job/20289008284
> remote: Permission to mercari/spanner-autoscaler.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/mercari/spanner-autoscaler/': The requested URL returned error: 403
=> Update to `permissions.contents = write` of create git tag action

.github/release.yml
=> Exclude dependabot PRs from release-notes

Dockerfile
`go.mod` has version `1.24` but dockerfile has `1.22` which causes image build failure. Therefore, use latest version in Dockerfile by default (because `go build` is backward compatible since introduction of toolchain feature).
Fixes #
=> Fix dockerfile Golang version
